
[page_set_up]
title = 'A binary guide to index investment'
select_ind_text = 'Whate index would you like to analyse'
select_start_text = "What day would you like the analysis to depart from ?"
cache_button = 'Clear cache'
section_1_header = ' Prices'
section_2_header = 'One day ahead forecasting output'
tab_options = ["Kalman Filter", "ARMA", "Hidden Markov Model"]

[indices]
EURO_STOXX_50 = ['EURO STOXX 50', '^STOXX50E']
FTSE_100 = ['FTSE 100', '^FTSE']
OMX_Stockholm_30 = ['OMX Stockholm 30', '^OMX']
CAC_40 = ['CAC 40', '^FCHI']
DAX = ['DAX', '^GDAXI']
MDAX = ['MDAX', '^MDAXI']
TECDAX = ['TECDAX', '^TECDAX']
IBEX_35 = ['IBEX 35', '^IBEX']
SP_500 = ['S&P 500', '^GSPC']
DOW_JONES = ['DOW JONES', '^DJI']
AEX = ['AEX', '^AEX']
NASDAQ_100 = ['NASDAQ 100', '^IXIC']

[data]
lead_suffix = 'lead'
train_test_size = 0.9
outlier_std_interval = 5
n_largest_composits = 3
p_max = 2
q_max = 2

[default_values]
pull_start_date = [2020, 1, 1]
kf_cv_samples = 10
kf_analysis_time = 10
kf_measurement_noise = 0.01
hmm_no_states = 3
hmm_cv_samples = 200
hmm_start_init = 2 # 20
hmm_cv_sample_sizes = [30, 60]
arma_analaysis_time_days = 35

[streamlit_sliders]
kf_measurement_noise = [0, 0.5, 0.01]
kf_analysis_time = [5, 55, 5]
kf_cv_samples = [0, 80]
hmm_no_states = [1, 6]
hmm_cv_samples = [50, 10_050, 50]
hmm_start_init = [0, 110, 1]

[streamlit_sliders_text]
kf_measurement_noise = 'Kalman Filter measurement noise'
kf_analysis_time = "How many weeks would you like the analysis to run on?"
kf_cv_samples = "How many cross validation samples should be taken?"
hmm_no_states = "How many hidden states should be identified?"
hmm_cv_samples = "How many cross validation samples should be taken?"
hmm_start_init = "What initialisation value should be passed to the HMM?"